### ISSUE TITLE
Page Block Not Appearing

### ISSUE THREAD

**Issue by Bosterm** [Libnamic/Omeka-S-FieldAsTags#1]
Hello,

This is a great plugin, but I am having trouble getting the page block to appear. The tags are appearing in the item browse view, but the "TagBrowsePreview" page block is not listed as an available page block when I try to add a page block to page. I'm not sure if this is a bug or if I'm not doing something correctly.

Thank you!

**Comment by Boca13** [comment]
Hello @Bosterm,

Thank you for warning us. Indeed, there was a missing setting in the module.config.php file that prevented the block from showing up in the block list.

I released a new version that corrects the problem. Look for a block called "Tag Browse Preview"

Please try it out and let me know if you have further trouble or if there's anything else that I can help you with,

Thank you.
